# Use -I to specify include path
fixedpoint:
	g++ -Wall fixedpoint.cpp -o fixedpoint.out

newtonraphson:
	g++ -Wall newtonraphson.cpp -o newtonraphson.out

secant:
	g++ -Wall secant.cpp -o secant.out

.PHONY: clean
clean:
	rm -fv *.o *.out