# (Use -I to specify include path)
fixedpoint: fixedpoint.cpp
	g++ -Wall fixedpoint.cpp -o fixedpoint

newtonraphson: newtonraphson.cpp
	g++ -Wall newtonraphson.cpp -o newtonraphson

secant: secant.cpp
	g++ -Wall secant.cpp -o secant

bisection: bisection.cpp
	g++ -Wall bisection.cpp -o bisection

falseposition: falseposition.cpp
	g++ -Wall falseposition.cpp -o falseposition

.PHONY: clean
clean:
	rm -fv *.o fixedpoint newtonraphson secant bisection falseposition